/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取当前会话 */
        get: operations["getSession"];
        put?: never;
        /** 登录 */
        post: operations["createSession"];
        /** 退出登录 */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新认证并轮换会话 */
        post: operations["reauthenticateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询文章列表
         * @description 支持标题搜索、状态筛选和分页；每页默认 20 篇。
         */
        get: operations["listArticles"];
        put?: never;
        /** 创建草稿 */
        post: operations["createArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章内部 ID。 */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        /** 读取文章编辑数据 */
        get: operations["getArticle"];
        /**
         * 保存完整文章编辑状态
         * @description 更新和发布均使用记录 version 做乐观锁校验。
         */
        put: operations["updateArticle"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章内部 ID。 */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 原子发布文章
         * @description 携带完整编辑状态保存并发布文章。
         */
        post: operations["publishArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章内部 ID。 */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤回文章 */
        post: operations["withdrawArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询项目分组 */
        get: operations["listProjects"];
        put?: never;
        /** 创建隐藏项目 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目内部 ID。 */
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /** 读取项目编辑数据 */
        get: operations["getProject"];
        /** 保存完整项目编辑状态 */
        put: operations["updateProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目内部 ID。 */
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 原子公开项目
         * @description 携带完整项目表单并在排序集合锁内追加公开项目。
         */
        post: operations["publishProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目内部 ID。 */
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 隐藏项目 */
        post: operations["hideProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 原子保存公开项目顺序 */
        put: operations["updateProjectOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传媒体资源 */
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 媒体资源公开 ULID。 */
                id: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        /** 读取媒体资源 */
        get: operations["getMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Crockford Base32 编码的公开 ULID。 */
        ULID: string;
        ProblemDetails: {
            /** Format: uri-reference */
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            /**
             * @description 稳定机器可读错误码。
             * @enum {string}
             */
            code: "validation_failed" | "authentication_required" | "session_expired" | "csrf_failed" | "version_conflict" | "github_repository_invalid" | "github_verification_unavailable" | "upload_too_large" | "upload_type_invalid" | "image_dimensions_exceeded" | "save_failed";
            request_id: string;
            errors: {
                [key: string]: string[];
            };
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        ReauthRequest: {
            /** Format: password */
            password: string;
        };
        Session: {
            /** Format: int64 */
            admin_id: number;
            username: string;
            csrf_token: string;
            /** Format: date-time */
            last_seen_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            absolute_expires_at: string;
        };
        ArticleSummary: {
            /** Format: int64 */
            id: number;
            public_ulid?: components["schemas"]["ULID"] | null;
            title: string;
            /** @enum {string} */
            status: "draft" | "published";
            /** Format: date-time */
            first_published_at?: string | null;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ArticleEdit: {
            /** Format: int64 */
            id: number;
            public_ulid?: components["schemas"]["ULID"] | null;
            title: string;
            body_markdown?: string | null;
            readonly body_html?: string | null;
            readonly toc_json?: Record<string, never>;
            readonly preview_text?: string | null;
            readonly renderer_version?: string | null;
            /** @enum {string} */
            status: "draft" | "published";
            /** Format: date-time */
            readonly first_published_at?: string | null;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ArticleWriteRequest: {
            title: string;
            /** @description 草稿可为空；发布时必须为非空正文。 */
            body_markdown: string | null;
            /**
             * Format: int64
             * @description 更新、发布和撤回时必填的乐观锁版本。
             */
            version?: number;
        };
        ProjectEdit: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: uri */
            github_url?: string | null;
            image_asset_id?: components["schemas"]["ULID"] | null;
            /** @enum {string} */
            status: "hidden" | "public";
            /** Format: int64 */
            sort_order?: number | null;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ProjectWriteRequest: {
            name: string;
            /** Format: uri */
            github_url?: string | null;
            image_asset_id?: components["schemas"]["ULID"] | null;
            /**
             * Format: int64
             * @description 更新、公开和隐藏时必填的乐观锁版本。
             */
            version?: number;
        };
        ProjectGroups: {
            public: components["schemas"]["ProjectEdit"][];
            hidden: components["schemas"]["ProjectEdit"][];
            /** Format: int64 */
            order_version: number;
        };
        ProjectOrderRequest: {
            /** Format: int64 */
            order_version: number;
            project_ids: number[];
        };
        MediaAsset: {
            id: components["schemas"]["ULID"];
            /** Format: uri-reference */
            preview_url: string;
            markdown_reference: string;
            source_media_type: string;
            stored_media_type: string;
            /** Format: int64 */
            byte_size: number;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            sha256?: string;
            /** Format: date-time */
            created_at: string;
        };
        PaginationMeta: {
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            per_page: number;
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            total_pages: number;
        };
        ArticleListResponse: {
            items: components["schemas"]["ArticleSummary"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
    };
    responses: {
        /** @description 请求成功。 */
        OK: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"] | components["schemas"]["ArticleListResponse"] | components["schemas"]["ArticleEdit"] | components["schemas"]["ProjectGroups"] | components["schemas"]["ProjectEdit"] | components["schemas"]["MediaAsset"];
            };
        };
        /** @description 资源创建成功。 */
        Created: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ArticleEdit"] | components["schemas"]["ProjectEdit"] | components["schemas"]["MediaAsset"];
            };
        };
        /** @description 请求成功，无响应正文。 */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 请求语法错误。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 未登录、凭据无效或会话已过期。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 已登录但没有权限或 CSRF 校验失败。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 资源不存在。 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 版本或排序集合版本冲突。 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 请求体或上传文件过大。 */
        RequestEntityTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 不支持的请求媒体类型。 */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 字段或业务校验失败。 */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 请求过于频繁。 */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 服务器内部错误。 */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 数据库或必要依赖暂时不可用。 */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description 文章内部 ID。 */
        ArticleID: number;
        /** @description 项目内部 ID。 */
        ProjectID: number;
        /** @description 媒体资源公开 ULID。 */
        MediaID: components["schemas"]["ULID"];
        Page: number;
        PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    reauthenticateSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReauthRequest"];
            };
        };
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listArticles: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
                /** @description 标题搜索词 */
                q?: string;
                status?: "draft" | "published";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createArticle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleWriteRequest"];
            };
        };
        responses: {
            201: components["responses"]["Created"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["RequestEntityTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章内部 ID。 */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章内部 ID。 */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleWriteRequest"];
            };
        };
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["RequestEntityTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    publishArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章内部 ID。 */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleWriteRequest"];
            };
        };
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["RequestEntityTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    withdrawArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章内部 ID。 */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectWriteRequest"];
            };
        };
        responses: {
            201: components["responses"]["Created"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目内部 ID。 */
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目内部 ID。 */
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectWriteRequest"];
            };
        };
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    publishProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目内部 ID。 */
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectWriteRequest"];
            };
        };
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    hideProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目内部 ID。 */
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateProjectOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectOrderRequest"];
            };
        };
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 图片文件。
                     */
                    file: string;
                };
            };
        };
        responses: {
            201: components["responses"]["Created"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["RequestEntityTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 媒体资源公开 ULID。 */
                id: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
