// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countPublishedArticles = `-- name: CountPublishedArticles :one
SELECT COUNT(*) AS total
FROM articles
WHERE status = 'published'
`

func (q *Queries) CountPublishedArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedArticles)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createArticle = `-- name: CreateArticle :execresult
INSERT INTO articles (
    title,
    body_markdown,
    status,
    version,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    'draft',
    1,
    ?,
    ?
)
`

type CreateArticleParams struct {
	Title        string         `json:"title"`
	BodyMarkdown sql.NullString `json:"body_markdown"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createArticle,
		arg.Title,
		arg.BodyMarkdown,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT
    id,
    public_ulid,
    title,
    body_markdown,
    body_html,
    toc_json,
    preview_text,
    renderer_version,
    status,
    first_published_at,
    version,
    created_at,
    updated_at
FROM articles
WHERE id = ?
`

func (q *Queries) GetArticleByID(ctx context.Context, id uint64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.PublicUlid,
		&i.Title,
		&i.BodyMarkdown,
		&i.BodyHtml,
		&i.TocJson,
		&i.PreviewText,
		&i.RendererVersion,
		&i.Status,
		&i.FirstPublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT
    id,
    public_ulid,
    title,
    status,
    first_published_at,
    version,
    created_at,
    updated_at
FROM articles
WHERE status = 'published'
ORDER BY first_published_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListPublishedArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedArticlesRow struct {
	ID               uint64         `json:"id"`
	PublicUlid       sql.NullString `json:"public_ulid"`
	Title            string         `json:"title"`
	Status           string         `json:"status"`
	FirstPublishedAt sql.NullTime   `json:"first_published_at"`
	Version          uint64         `json:"version"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]ListPublishedArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesRow{}
	for rows.Next() {
		var i ListPublishedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicUlid,
			&i.Title,
			&i.Status,
			&i.FirstPublishedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :execresult
UPDATE articles
SET public_ulid = ?,
    title = ?,
    body_markdown = ?,
    body_html = ?,
    toc_json = ?,
    preview_text = ?,
    renderer_version = ?,
    status = ?,
    first_published_at = ?,
    version = version + 1,
    updated_at = ?
WHERE id = ?
  AND version = ?
`

type UpdateArticleParams struct {
	PublicUlid       sql.NullString  `json:"public_ulid"`
	Title            string          `json:"title"`
	BodyMarkdown     sql.NullString  `json:"body_markdown"`
	BodyHtml         sql.NullString  `json:"body_html"`
	TocJson          json.RawMessage `json:"toc_json"`
	PreviewText      sql.NullString  `json:"preview_text"`
	RendererVersion  sql.NullString  `json:"renderer_version"`
	Status           string          `json:"status"`
	FirstPublishedAt sql.NullTime    `json:"first_published_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	ID               uint64          `json:"id"`
	Version          uint64          `json:"version"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateArticle,
		arg.PublicUlid,
		arg.Title,
		arg.BodyMarkdown,
		arg.BodyHtml,
		arg.TocJson,
		arg.PreviewText,
		arg.RendererVersion,
		arg.Status,
		arg.FirstPublishedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
}
