// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) AS total
FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAdmin = `-- name: CreateAdmin :execresult
INSERT INTO admins (
    username,
    password_hash,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?
)
`

type CreateAdminParams struct {
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAdmin,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createAdminSession = `-- name: CreateAdminSession :execresult
INSERT INTO admin_sessions (
    token_hash,
    admin_id,
    csrf_hash,
    last_seen_at,
    absolute_expires_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateAdminSessionParams struct {
	TokenHash         []byte    `json:"token_hash"`
	AdminID           uint64    `json:"admin_id"`
	CsrfHash          []byte    `json:"csrf_hash"`
	LastSeenAt        time.Time `json:"last_seen_at"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAdminSession,
		arg.TokenHash,
		arg.AdminID,
		arg.CsrfHash,
		arg.LastSeenAt,
		arg.AbsoluteExpiresAt,
		arg.CreatedAt,
	)
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT
    id,
    username,
    password_hash,
    created_at,
    updated_at
FROM admins
WHERE username = ?
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminSessionByTokenHash = `-- name: GetAdminSessionByTokenHash :one
SELECT
    s.id,
    s.token_hash,
    s.admin_id,
    s.csrf_hash,
    s.last_seen_at,
    s.absolute_expires_at,
    s.revoked_at,
    s.created_at,
    a.username
FROM admin_sessions AS s
JOIN admins AS a ON a.id = s.admin_id
WHERE s.token_hash = ?
  AND s.revoked_at IS NULL
`

type GetAdminSessionByTokenHashRow struct {
	ID                uint64       `json:"id"`
	TokenHash         []byte       `json:"token_hash"`
	AdminID           uint64       `json:"admin_id"`
	CsrfHash          []byte       `json:"csrf_hash"`
	LastSeenAt        time.Time    `json:"last_seen_at"`
	AbsoluteExpiresAt time.Time    `json:"absolute_expires_at"`
	RevokedAt         sql.NullTime `json:"revoked_at"`
	CreatedAt         time.Time    `json:"created_at"`
	Username          string       `json:"username"`
}

func (q *Queries) GetAdminSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetAdminSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminSessionByTokenHash, tokenHash)
	var i GetAdminSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AdminID,
		&i.CsrfHash,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const revokeAdminSession = `-- name: RevokeAdminSession :execresult
UPDATE admin_sessions
SET revoked_at = ?
WHERE id = ?
  AND revoked_at IS NULL
`

type RevokeAdminSessionParams struct {
	RevokedAt sql.NullTime `json:"revoked_at"`
	ID        uint64       `json:"id"`
}

func (q *Queries) RevokeAdminSession(ctx context.Context, arg RevokeAdminSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeAdminSession, arg.RevokedAt, arg.ID)
}

const touchAdminSession = `-- name: TouchAdminSession :execresult
UPDATE admin_sessions
SET last_seen_at = ?
WHERE id = ?
  AND revoked_at IS NULL
`

type TouchAdminSessionParams struct {
	LastSeenAt time.Time `json:"last_seen_at"`
	ID         uint64    `json:"id"`
}

func (q *Queries) TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, touchAdminSession, arg.LastSeenAt, arg.ID)
}
