// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createMediaAsset = `-- name: CreateMediaAsset :execresult
INSERT INTO media_assets (
    id,
    storage_key,
    source_media_type,
    stored_media_type,
    byte_size,
    width,
    height,
    sha256,
    created_by,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateMediaAssetParams struct {
	ID              string    `json:"id"`
	StorageKey      string    `json:"storage_key"`
	SourceMediaType string    `json:"source_media_type"`
	StoredMediaType string    `json:"stored_media_type"`
	ByteSize        uint64    `json:"byte_size"`
	Width           uint32    `json:"width"`
	Height          uint32    `json:"height"`
	Sha256          []byte    `json:"sha256"`
	CreatedBy       uint64    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMediaAsset,
		arg.ID,
		arg.StorageKey,
		arg.SourceMediaType,
		arg.StoredMediaType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.Sha256,
		arg.CreatedBy,
		arg.CreatedAt,
	)
}

const deleteArticleMediaByArticleID = `-- name: DeleteArticleMediaByArticleID :exec
DELETE FROM article_media
WHERE article_id = ?
`

func (q *Queries) DeleteArticleMediaByArticleID(ctx context.Context, articleID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteArticleMediaByArticleID, articleID)
	return err
}

const getMediaAssetByID = `-- name: GetMediaAssetByID :one
SELECT
    id,
    storage_key,
    source_media_type,
    stored_media_type,
    byte_size,
    width,
    height,
    sha256,
    created_by,
    created_at
FROM media_assets
WHERE id = ?
`

func (q *Queries) GetMediaAssetByID(ctx context.Context, id string) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAssetByID, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.SourceMediaType,
		&i.StoredMediaType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertArticleMedia = `-- name: InsertArticleMedia :exec
INSERT INTO article_media (article_id, asset_id, alt_text)
VALUES (
    ?,
    ?,
    ?
)
`

type InsertArticleMediaParams struct {
	ArticleID uint64 `json:"article_id"`
	AssetID   string `json:"asset_id"`
	AltText   string `json:"alt_text"`
}

func (q *Queries) InsertArticleMedia(ctx context.Context, arg InsertArticleMediaParams) error {
	_, err := q.db.ExecContext(ctx, insertArticleMedia, arg.ArticleID, arg.AssetID, arg.AltText)
	return err
}

const isMediaReferencedByPublicProject = `-- name: IsMediaReferencedByPublicProject :one
SELECT EXISTS (
    SELECT 1
    FROM projects AS p
    WHERE p.image_asset_id = ?
      AND p.status = 'public'
) AS is_referenced
`

func (q *Queries) IsMediaReferencedByPublicProject(ctx context.Context, assetID sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMediaReferencedByPublicProject, assetID)
	var is_referenced bool
	err := row.Scan(&is_referenced)
	return is_referenced, err
}

const isMediaReferencedByPublishedArticle = `-- name: IsMediaReferencedByPublishedArticle :one
SELECT EXISTS (
    SELECT 1
    FROM article_media AS am
    JOIN articles AS a ON a.id = am.article_id
    WHERE am.asset_id = ?
      AND a.status = 'published'
) AS is_referenced
`

func (q *Queries) IsMediaReferencedByPublishedArticle(ctx context.Context, assetID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMediaReferencedByPublishedArticle, assetID)
	var is_referenced bool
	err := row.Scan(&is_referenced)
	return is_referenced, err
}
