// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Admin struct {
	ID           uint64    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type AdminSession struct {
	ID                uint64       `json:"id"`
	TokenHash         []byte       `json:"token_hash"`
	AdminID           uint64       `json:"admin_id"`
	CsrfHash          []byte       `json:"csrf_hash"`
	LastSeenAt        time.Time    `json:"last_seen_at"`
	AbsoluteExpiresAt time.Time    `json:"absolute_expires_at"`
	RevokedAt         sql.NullTime `json:"revoked_at"`
	CreatedAt         time.Time    `json:"created_at"`
}

type Article struct {
	ID               uint64          `json:"id"`
	PublicUlid       sql.NullString  `json:"public_ulid"`
	Title            string          `json:"title"`
	BodyMarkdown     sql.NullString  `json:"body_markdown"`
	BodyHtml         sql.NullString  `json:"body_html"`
	TocJson          json.RawMessage `json:"toc_json"`
	PreviewText      sql.NullString  `json:"preview_text"`
	RendererVersion  sql.NullString  `json:"renderer_version"`
	Status           string          `json:"status"`
	FirstPublishedAt sql.NullTime    `json:"first_published_at"`
	Version          uint64          `json:"version"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type ArticleMedium struct {
	ArticleID uint64 `json:"article_id"`
	AssetID   string `json:"asset_id"`
	AltText   string `json:"alt_text"`
}

type MediaAsset struct {
	ID              string    `json:"id"`
	StorageKey      string    `json:"storage_key"`
	SourceMediaType string    `json:"source_media_type"`
	StoredMediaType string    `json:"stored_media_type"`
	ByteSize        uint64    `json:"byte_size"`
	Width           uint32    `json:"width"`
	Height          uint32    `json:"height"`
	Sha256          []byte    `json:"sha256"`
	CreatedBy       uint64    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
}

type Project struct {
	ID           uint64         `json:"id"`
	Name         string         `json:"name"`
	GithubUrl    sql.NullString `json:"github_url"`
	ImageAssetID sql.NullString `json:"image_asset_id"`
	Status       string         `json:"status"`
	SortOrder    sql.NullInt64  `json:"sort_order"`
	Version      uint64         `json:"version"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type ProjectOrderState struct {
	ID        uint8     `json:"id"`
	Version   uint64    `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}
