// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountPublicProjects(ctx context.Context) (int64, error)
	CountPublishedArticles(ctx context.Context) (int64, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (sql.Result, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (sql.Result, error)
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (sql.Result, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error)
	DeleteArticleMediaByArticleID(ctx context.Context, articleID uint64) error
	GetAdminByUsername(ctx context.Context, username string) (Admin, error)
	GetAdminSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetAdminSessionByTokenHashRow, error)
	GetArticleByID(ctx context.Context, id uint64) (Article, error)
	GetMediaAssetByID(ctx context.Context, id string) (MediaAsset, error)
	GetProjectByID(ctx context.Context, id uint64) (Project, error)
	GetProjectOrderStateForUpdate(ctx context.Context) (ProjectOrderState, error)
	InsertArticleMedia(ctx context.Context, arg InsertArticleMediaParams) error
	IsMediaReferencedByPublicProject(ctx context.Context, assetID sql.NullString) (bool, error)
	IsMediaReferencedByPublishedArticle(ctx context.Context, assetID string) (bool, error)
	ListPublicProjectIDsForUpdate(ctx context.Context) ([]uint64, error)
	ListPublicProjects(ctx context.Context, arg ListPublicProjectsParams) ([]Project, error)
	ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]ListPublishedArticlesRow, error)
	RevokeAdminSession(ctx context.Context, arg RevokeAdminSessionParams) (sql.Result, error)
	TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) (sql.Result, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (sql.Result, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error)
	UpdateProjectOrderState(ctx context.Context, arg UpdateProjectOrderStateParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
