// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountAdminArticles(ctx context.Context, arg CountAdminArticlesParams) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountPublicProjects(ctx context.Context) (int64, error)
	CountPublishedArticles(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (sql.Result, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (sql.Result, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (sql.Result, error)
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (sql.Result, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error)
	DeleteArticleMediaByArticleID(ctx context.Context, articleID uint64) error
	GetAdminByUsername(ctx context.Context, username string) (Admin, error)
	GetAdminSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetAdminSessionByTokenHashRow, error)
	GetArticleByID(ctx context.Context, id uint64) (Article, error)
	GetMaxPublicProjectSortOrder(ctx context.Context) (sql.NullInt64, error)
	GetMediaAssetByID(ctx context.Context, id string) (MediaAsset, error)
	GetProjectByID(ctx context.Context, id uint64) (Project, error)
	GetProjectByIDForUpdate(ctx context.Context, id uint64) (Project, error)
	GetProjectOrderState(ctx context.Context) (ProjectOrderState, error)
	GetProjectOrderStateForUpdate(ctx context.Context) (ProjectOrderState, error)
	GetPublishedArticleByULID(ctx context.Context, publicUlid sql.NullString) (Article, error)
	HideProject(ctx context.Context, arg HideProjectParams) (sql.Result, error)
	InsertArticleMedia(ctx context.Context, arg InsertArticleMediaParams) error
	IsMediaReferencedByPublicProject(ctx context.Context, assetID sql.NullString) (bool, error)
	IsMediaReferencedByPublishedArticle(ctx context.Context, assetID string) (bool, error)
	ListAdminArticles(ctx context.Context, arg ListAdminArticlesParams) ([]ListAdminArticlesRow, error)
	ListAdminHiddenProjects(ctx context.Context) ([]Project, error)
	ListAdminPublicProjects(ctx context.Context) ([]Project, error)
	ListAllPublicProjects(ctx context.Context) ([]Project, error)
	ListPublicProjectIDsForUpdate(ctx context.Context) ([]uint64, error)
	ListPublicProjects(ctx context.Context, arg ListPublicProjectsParams) ([]Project, error)
	ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]ListPublishedArticlesRow, error)
	PublishProject(ctx context.Context, arg PublishProjectParams) (sql.Result, error)
	RevokeAdminSession(ctx context.Context, arg RevokeAdminSessionParams) (sql.Result, error)
	SetProjectSortOrder(ctx context.Context, arg SetProjectSortOrderParams) (sql.Result, error)
	SetProjectSortOrderTemporary(ctx context.Context, arg SetProjectSortOrderTemporaryParams) (sql.Result, error)
	TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) (sql.Result, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (sql.Result, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error)
	UpdateProjectOrderState(ctx context.Context, arg UpdateProjectOrderStateParams) (sql.Result, error)
	WithdrawArticle(ctx context.Context, arg WithdrawArticleParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
